# Generated by Django 5.0.3 on 2024-05-03 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=200)),
                ('bus_no', models.CharField(max_length=200)),
                ('bus_registration_no', models.CharField(max_length=200)),
                ('setting_capacity', models.CharField(max_length=200)),
                ('standing_capacity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=200)),
                ('route_start', models.CharField(max_length=200)),
                ('route_end', models.CharField(max_length=200)),
                ('distance', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=200)),
                ('driver_id', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=200)),
                ('duty_timing', models.CharField(max_length=200)),
                ('driver_status', models.CharField(max_length=200)),
                ('bus_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminSide.buses')),
            ],
        ),
        migrations.CreateModel(
            name='PassPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_price', models.CharField(max_length=200)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminSide.busroute')),
            ],
        ),
    ]
