# Generated by Django 5.0.3 on 2024-05-14 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passprice',
            name='pass_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='PassApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_start_date', models.DateField()),
                ('pass_end_date', models.DateField()),
                ('pass_status', models.CharField(default=0, max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('renew_date', models.DateField()),
                ('pass_price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminSide.passprice')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
