# Generated by Django 5.0.3 on 2024-05-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0003_enquiries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passapplications',
            options={'ordering': ['-create_date']},
        ),
        migrations.AddField(
            model_name='enquiries',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
