# Generated by Django 5.0.3 on 2024-05-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0005_enquiries_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passapplications',
            name='document',
            field=models.ImageField(default='', upload_to='pass_document'),
        ),
        migrations.AddField(
            model_name='passapplications',
            name='mobile_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='passapplications',
            name='profile_image',
            field=models.ImageField(default='', upload_to='pass_profile'),
        ),
    ]
