# Generated by Django 5.0.3 on 2024-05-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0006_passapplications_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passapplications',
            name='renew_date',
            field=models.DateField(default=''),
        ),
    ]
