# Generated by Django 5.0.3 on 2024-05-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0007_alter_passapplications_renew_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passapplications',
            name='pass_end_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='passapplications',
            name='pass_start_date',
            field=models.CharField(max_length=200),
        ),
    ]
