# Generated by Django 5.0.3 on 2024-05-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0008_alter_passapplications_pass_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passapplications',
            name='renew_date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
