# Generated by Django 5.0.3 on 2024-05-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0010_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='passprice',
            name='final_half_price',
            field=models.CharField(default='', max_length=200),
        ),
    ]
